<?php 
session_start();
session_regenerate_id();
include('../webadmin/inc/connection.inc.php');
include('../webadmin/inc/function.inc.php');
isUSER();
unset($_SESSION['USER_LOGIN']);
unset($_SESSION['USER_ID']);
redirect('login.php');
?>